#data ingestion config
data_ingestion:
  raw_data: Source\data\cleaned_data.json
  clean_data: Source\data\cleaned_data.json

model:
  name: gpt-4.1-mini-2025-04-14
  
chunking:
  chunk_size: 1000
  chunk_overlap: 100