#data ingestion config
data_source:
  excel_sheet: Source\data\Final.xlsx
  processed_data:
    petrol_vehicle_data: Source\data\processed_data\petrol_vehicle.csv
    electric_vehicle_data: Source\data\processed_data\ev.csv
    price_data: Source\data\processed_data\price.csv